path_cl: 'cl.exe'
path_ml64:  'ml64.exe'

path_masmshc:  'C:\Users\hacker\Source\Repos\masm_shc\out\build\x64-Debug\masm_shc\masm_shc.exe'
path_runshc: 'C:\Users\hacker\Source\Repos\masm_shc\out\build\x64-Debug\runshc\runshc.exe'
#- path_shexec = r'C:\Research\hasherezade\exec_fiber\sh-exec-fiber.exe'

path_sgn: 'C:\tools\sgn2.1\sgn.exe'

#avred_server: "http://192.168.88.65:8001"
avred_server: ""

# leave empty for random on each build
xor_key: ""
xor_key2: ""
#xor_key: "\x42"
#xor_key2: "\x13\x37"
